name: Tests
on: [push, pull_request]
permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: 1.19.x

    - name: Tests
      run: go test -v -race -cover -coverprofile=coverage.out -covermode=atomic ./...


    - name: Update Coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out
